package vista.paneles;

import controlador.paneles.CPPrincipal;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JLabel;

/**
 * Panel de inicio de la aplicación.
 * Este panel muestra la pantalla de inicio de la aplicación.
 * Permite al usuario navegar por las funciones principales.
 * @author Tomás González Martín
 */
public class PanelInicio extends javax.swing.JPanel {

    private controlador.paneles.CPPrincipal C;
    /**
     * Crea un nuevo Panel de Inicio con el idioma especificado.
     * @param idioma El idioma utilizado en la interfaz.
     */
    public PanelInicio(Locale idioma) {
        initComponents();
        C = new CPPrincipal(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCentral = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbl_inicio_titulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(38, 38, 38));
        setAutoscrolls(true);
        setMinimumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(1536, 730));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCentral.setBackground(new java.awt.Color(38, 38, 38));
        panelCentral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Abstract Design.png"))); // NOI18N
        panelCentral.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 284, 1210, 446));

        lbl_inicio_titulo.setFont(new java.awt.Font("Verdana", 1, 68)); // NOI18N
        lbl_inicio_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_inicio_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_inicio_titulo.setText("<html><div style='text-align: center;'> Organiza tus servicios, peliculas, libros y musicas en unico lugar </div></html> ");
        panelCentral.add(lbl_inicio_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 28, 929, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/InicioFondo.png"))); // NOI18N
        panelCentral.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 730));

        add(panelCentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 0, 1210, 730));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_inicio_titulo;
    private javax.swing.JPanel panelCentral;
    // End of variables declaration//GEN-END:variables
    /**
    * Actualiza el idioma de la interfaz utilizando el ResourceBundle proporcionado.
    * @param bundle El ResourceBundle que contiene las cadenas de texto en el idioma deseado.
    */
    public void actualizarIdioma(ResourceBundle bundle) {
        C.actualizarIdioma(bundle);
    }
    /**
     * Obtiene el JLabel que muestra el título de inicio.
     * @return El JLabel que muestra el título de inicio.
     */
    public JLabel getLbl_inicio_titulo() {
        return lbl_inicio_titulo;
    }
    /**
     * Establece el JLabel que muestra el título de inicio con el JLabel proporcionado.
     * @param lbl_inicio_titulo El JLabel que muestra el título de inicio.
     */
    public void setLbl_inicio_titulo(JLabel lbl_inicio_titulo) {
        this.lbl_inicio_titulo = lbl_inicio_titulo;
    }
    
}
