package vista.frames;

import controlador.ConBDD;
import controlador.UDiseño;
import controlador.frames.CInsercion;
import controlador.paneles.CPLibros;
import java.util.Locale;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import modelo.Usuario;


/**
 * Frame de inserción de libros.
 * Permite al usuario seleccionar un libro y asignarle una puntuación.
 * Proporciona funcionalidades para guardar la inserción y cerrar la ventana.
 * Además, gestiona el diseño y la interacción con el usuario.
 * 
 * @author Tomas Gonzalez Martin
 */
public class FInsert extends javax.swing.JFrame {

    private Usuario user;
    private final ConBDD con;
    private CPLibros fa;
    private final CInsercion c;
    private int xMouse;
    private int yMouse;
    /**
     * Crea un nuevo frame de inserción de libros.
     * 
     * @param user Usuario actual.
     * @param con Conexión a la base de datos.
     * @param idioma Idioma utilizado en la interfaz.
     * @param fa Controlador de la lista de libros.
     */ 
    public FInsert(Usuario user, ConBDD con, Locale idioma, CPLibros fa) {
        initComponents();
        this.user = user;
        this.con = con;
        this.setLocale(idioma);
        this.fa = fa;
        this.c = new CInsercion(this);
        
        UDiseño.estilizarBtn(btnGuardar);
        UDiseño.estilizarTextField(tFPuntuacion);
        UDiseño.redondearElemento(cb);
        UDiseño.redondearVentana(this);
        
        setIconImage(UDiseño.createImageIcon("/img/logo_myapp/Logo_Nav.png", "Logo").getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cb = new javax.swing.JComboBox<>();
        lbl_insert_puntuacion = new javax.swing.JLabel();
        tFPuntuacion = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        lbl_insert_titulo = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        panelDesplazamiento = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(390, 305));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(26, 26, 26));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cb.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jPanel1.add(cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 71, 235, 45));

        lbl_insert_puntuacion.setText("Puntuacion");
        jPanel1.add(lbl_insert_puntuacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 134, -1, -1));

        tFPuntuacion.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jPanel1.add(tFPuntuacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 162, 235, 37));

        btnGuardar.setBackground(new java.awt.Color(158, 255, 0));
        btnGuardar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setText("Guardar");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 235, 235, 41));

        lbl_insert_titulo.setText("Titulo");
        jPanel1.add(lbl_insert_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 43, -1, -1));

        btnExit.setBackground(new java.awt.Color(26, 26, 26));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnExit.setForeground(new java.awt.Color(164, 164, 164));
        btnExit.setText("X");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setFocusable(false);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 40, 40));

        panelDesplazamiento.setBackground(new java.awt.Color(26, 26, 26));
        panelDesplazamiento.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelDesplazamientoMouseDragged(evt);
            }
        });
        panelDesplazamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelDesplazamientoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelDesplazamientoLayout = new javax.swing.GroupLayout(panelDesplazamiento);
        panelDesplazamiento.setLayout(panelDesplazamientoLayout);
        panelDesplazamientoLayout.setHorizontalGroup(
            panelDesplazamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        panelDesplazamientoLayout.setVerticalGroup(
            panelDesplazamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(panelDesplazamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Maneja el evento cuando el mouse entra en el botón de salida.
     * Cambia el estado del botón de salida.
     * 
     * @param evt El evento del mouse que activa la función.
     */
    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        c.cambiarEstadoBtnSalida(true);
    }//GEN-LAST:event_btnExitMouseEntered
    /**
     * Maneja el evento cuando el mouse sale del botón de salida.
     * Cambia el estado del botón de salida.
     * 
     * @param evt El evento del mouse que activa la función.
     */
    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        c.cambiarEstadoBtnSalida(false);
    }//GEN-LAST:event_btnExitMouseExited
    /**
     * Maneja el evento cuando se hace clic en el botón de salida.
     * Cierra la ventana actual.
     * 
     * @param evt El evento del mouse que activa la función.
     */
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        c.cerrar();
    }//GEN-LAST:event_btnExitActionPerformed
    /**
     * Maneja el evento cuando el mouse arrastra sobre el panel de desplazamiento.
     * Realiza un movimiento de pantalla según el movimiento del mouse.
     * 
     * @param evt El evento del mouse que activa la función.
     */
    private void panelDesplazamientoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDesplazamientoMouseDragged
        c.movimientoPorPantalla(evt);
    }//GEN-LAST:event_panelDesplazamientoMouseDragged
    /**
     * Maneja el evento cuando se presiona el mouse en el panel de desplazamiento.
     * Actualiza las coordenadas del mouse para el movimiento de la pantalla.
     * 
     * @param evt El evento del mouse que activa la función.
     */
    private void panelDesplazamientoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDesplazamientoMousePressed
        c.desplazamientoPressed(evt);
    }//GEN-LAST:event_panelDesplazamientoMousePressed
    /**
     * Maneja el evento cuando se hace clic en el botón de guardar.
     * Guarda la información ingresada y cierra la ventana.
     * 
     * @param evt El evento del mouse que activa la función.
     */
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        c.guardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnExit;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cb;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_insert_puntuacion;
    private javax.swing.JLabel lbl_insert_titulo;
    private javax.swing.JPanel panelDesplazamiento;
    private javax.swing.JTextField tFPuntuacion;
    // End of variables declaration//GEN-END:variables

    /**
     * Obtiene el usuario asociado a este marco.
     * 
     * @return El usuario asociado.
     */
    public Usuario getUser() {
        return user;
    }

    /**
     * Establece el usuario asociado a este marco.
     * 
     * @param user El usuario a establecer.
     */
    public void setUser(Usuario user) {
        this.user = user;
    }

    /**
     * Obtiene la posición x del mouse.
     * 
     * @return La posición x del mouse.
     */
    public int getxMouse() {
        return xMouse;
    }

    /**
     * Establece la posición x del mouse.
     * 
     * @param xMouse La posición x del mouse a establecer.
     */
    public void setxMouse(int xMouse) {
        this.xMouse = xMouse;
    }

    /**
     * Obtiene la posición y del mouse.
     * 
     * @return La posición y del mouse.
     */
    public int getyMouse() {
        return yMouse;
    }

    /**
     * Establece la posición y del mouse.
     * 
     * @param yMouse La posición y del mouse a establecer.
     */
    public void setyMouse(int yMouse) {
        this.yMouse = yMouse;
    }

    /**
     * Obtiene el botón de salida.
     * 
     * @return El botón de salida.
     */
    public JButton getBtnExit() {
        return btnExit;
    }

    /**
     * Establece el botón de salida.
     * 
     * @param btnExit El botón de salida a establecer.
     */
    public void setBtnExit(JButton btnExit) {
        this.btnExit = btnExit;
    }

    /**
     * Obtiene el botón de guardar.
     * 
     * @return El botón de guardar.
     */
    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    /**
     * Establece el botón de guardar.
     * 
     * @param btnGuardar El botón de guardar a establecer.
     */
    public void setBtnGuardar(JButton btnGuardar) {
        this.btnGuardar = btnGuardar;
    }

    /**
     * Obtiene el ComboBox.
     * 
     * @return El ComboBox.
     */
    public JComboBox<String> getCb() {
        return cb;
    }

    /**
     * Establece el ComboBox.
     * 
     * @param cb El ComboBox a establecer.
     */
    public void setCb(JComboBox<String> cb) {
        this.cb = cb;
    }

    /**
     * Obtiene la etiqueta de inserción de puntuación.
     * 
     * @return La etiqueta de inserción de puntuación.
     */
    public JLabel getLbl_insert_puntuacion() {
        return lbl_insert_puntuacion;
    }

    /**
     * Establece la etiqueta de inserción de puntuación.
     * 
     * @param lbl_insert_puntuacion La etiqueta de inserción de puntuación a establecer.
     */
    public void setLbl_insert_puntuacion(JLabel lbl_insert_puntuacion) {
        this.lbl_insert_puntuacion = lbl_insert_puntuacion;
    }

    /**
     * Obtiene la etiqueta de inserción de título.
     * 
     * @return La etiqueta de inserción de título.
     */
    public JLabel getLbl_insert_titulo() {
        return lbl_insert_titulo;
    }

    /**
     * Establece la etiqueta de inserción de título.
     * 
     * @param lbl_insert_titulo La etiqueta de inserción de título a establecer.
     */
    public void setLbl_insert_titulo(JLabel lbl_insert_titulo) {
        this.lbl_insert_titulo = lbl_insert_titulo;
    }

    /**
     * Obtiene el panel de desplazamiento.
     * 
     * @return El panel de desplazamiento.
     */
    public JPanel getPanelDesplazamiento() {
        return panelDesplazamiento;
    }

    /**
     * Establece el panel de desplazamiento.
     * 
     * @param panelDesplazamiento El panel de desplazamiento a establecer.
     */
    public void setPanelDesplazamiento(JPanel panelDesplazamiento) {
        this.panelDesplazamiento = panelDesplazamiento;
    }

    /**
     * Obtiene la conexión a la base de datos.
     * 
     * @return La conexión a la base de datos.
     */
    public ConBDD getCon() {
        return con;
    }

    /**
     * Obtiene el campo de texto para la puntuación.
     * 
     * @return El campo de texto para la puntuación.
     */
    public JTextField gettFPuntuacion() {
        return tFPuntuacion;
    }

    /**
     * Establece el campo de texto para la puntuación.
     * 
     * @param tFPuntuacion El campo de texto para la puntuación a establecer.
     */
    public void settFPuntuacion(JTextField tFPuntuacion) {
        this.tFPuntuacion = tFPuntuacion;
    }

    /**
     * Obtiene el controlador de paneles de libros asociado.
     * 
     * @return El controlador de paneles de libros.
     */
    public CPLibros getFa() {
        return fa;
    }

    /**
     * Establece el controlador de paneles de libros.
     * 
     * @param fa El controlador de paneles de libros a establecer.
     */
    public void setFa(CPLibros fa) {
        this.fa = fa;
    }
}