package vista.frames;

import controlador.ConexionBDD;
import controlador.ControladorCierreApp;

import controlador.ControladorRegistro;
import controlador.UtilDiseño;
import java.util.Locale;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Tomas Gonzalez Martin
 */

public class FrameRegistro extends javax.swing.JFrame {
    
    private int xMouse;
    private int yMouse;
    private final ControladorRegistro C_REG;
    private final ConexionBDD CON;
    /**
     * Creates new form VentanaRegistro
     * @param con
     */
    public FrameRegistro(ConexionBDD con, Locale idioma) {
        initComponents();
        
        this.CON = con;
        
        this.setLocale(idioma);
        
        C_REG = new ControladorRegistro(this);
        
        UtilDiseño.redondearVentana(this);
        
        UtilDiseño.estilizarTextFieldEmail(tFEmail);
        UtilDiseño.estilizarTextFieldUser(tFUser);
        UtilDiseño.estilizarTextFieldPassword(tFPassword);
        UtilDiseño.estilizarTextFieldPassword(tFPasswordValidacion);
        UtilDiseño.estilizarBtn(btnRegistro); 
                
        getRootPane().setDefaultButton(btnRegistro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelCentral = new javax.swing.JPanel();
        lbl_registro_titulo = new javax.swing.JLabel();
        lbl_registro_email = new javax.swing.JLabel();
        lbl_registro_password_r = new javax.swing.JLabel();
        lbl_registro_usuario = new javax.swing.JLabel();
        btnRegistro = new javax.swing.JButton();
        tFPasswordValidacion = new javax.swing.JPasswordField();
        tFUser = new javax.swing.JTextField();
        lblInicioSes = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        panelDesplazamiento = new javax.swing.JPanel();
        tFEmail = new javax.swing.JTextField();
        tFPassword = new javax.swing.JPasswordField();
        lbl_registro_password = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelCentral.setBackground(new java.awt.Color(26, 26, 26));
        panelCentral.setMinimumSize(new java.awt.Dimension(390, 637));
        panelCentral.setPreferredSize(new java.awt.Dimension(390, 637));
        panelCentral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_registro_titulo.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        lbl_registro_titulo.setForeground(new java.awt.Color(239, 239, 239));
        lbl_registro_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_registro_titulo.setText("Registrate gratis");
        panelCentral.add(lbl_registro_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 55, 341, 60));

        lbl_registro_email.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lbl_registro_email.setForeground(new java.awt.Color(164, 164, 164));
        lbl_registro_email.setText("Email");
        panelCentral.add(lbl_registro_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 150, -1, -1));

        lbl_registro_password_r.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lbl_registro_password_r.setForeground(new java.awt.Color(164, 164, 164));
        lbl_registro_password_r.setText("Repetir contraseña");
        panelCentral.add(lbl_registro_password_r, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 438, -1, -1));

        lbl_registro_usuario.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lbl_registro_usuario.setForeground(new java.awt.Color(164, 164, 164));
        lbl_registro_usuario.setText("Usuario");
        panelCentral.add(lbl_registro_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 250, -1, -1));

        btnRegistro.setBackground(new java.awt.Color(158, 255, 0));
        btnRegistro.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnRegistro.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistro.setText("Registrame");
        btnRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        panelCentral.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 547, 314, 50));

        tFPasswordValidacion.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        panelCentral.add(tFPasswordValidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 466, 314, 55));

        tFUser.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tFUser.setToolTipText("");
        panelCentral.add(tFUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 277, 314, 55));

        lblInicioSes.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblInicioSes.setForeground(new java.awt.Color(164, 164, 164));
        lblInicioSes.setText("Inicia sesion");
        lblInicioSes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblInicioSes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInicioSesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInicioSesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInicioSesMouseExited(evt);
            }
        });
        panelCentral.add(lblInicioSes, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 608, -1, -1));

        btnExit.setBackground(new java.awt.Color(26, 26, 26));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnExit.setForeground(new java.awt.Color(164, 164, 164));
        btnExit.setText("X");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setFocusable(false);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        panelCentral.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 40, 40));

        panelDesplazamiento.setBackground(new java.awt.Color(26, 26, 26));
        panelDesplazamiento.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelDesplazamientoMouseDragged(evt);
            }
        });
        panelDesplazamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelDesplazamientoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelDesplazamientoLayout = new javax.swing.GroupLayout(panelDesplazamiento);
        panelDesplazamiento.setLayout(panelDesplazamientoLayout);
        panelDesplazamientoLayout.setHorizontalGroup(
            panelDesplazamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        panelDesplazamientoLayout.setVerticalGroup(
            panelDesplazamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        panelCentral.add(panelDesplazamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 30));

        tFEmail.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tFEmail.setToolTipText("");
        panelCentral.add(tFEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 183, 314, 55));

        tFPassword.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        panelCentral.add(tFPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 371, 314, 55));

        lbl_registro_password.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lbl_registro_password.setForeground(new java.awt.Color(164, 164, 164));
        lbl_registro_password.setText("Contraseña");
        panelCentral.add(lbl_registro_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 344, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        ControladorCierreApp.cerrarApp();
    }//GEN-LAST:event_btnExitActionPerformed

    private void panelDesplazamientoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDesplazamientoMouseDragged
        C_REG.desplazamientoPressed(evt);
    }//GEN-LAST:event_panelDesplazamientoMouseDragged

    private void panelDesplazamientoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDesplazamientoMousePressed
        C_REG.movimientoPorPantalla(evt);
    }//GEN-LAST:event_panelDesplazamientoMousePressed

    private void lblInicioSesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInicioSesMouseClicked
        C_REG.abrirInicioSesion();
    }//GEN-LAST:event_lblInicioSesMouseClicked

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        C_REG.registrarUsuario();
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void lblInicioSesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInicioSesMouseEntered
        C_REG.cambiarEstadoLblInicio(true);
    }//GEN-LAST:event_lblInicioSesMouseEntered

    private void lblInicioSesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInicioSesMouseExited
        C_REG.cambiarEstadoLblInicio(false);
    }//GEN-LAST:event_lblInicioSesMouseExited

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        C_REG.cambiarEstadoBtnSalida(true);
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        C_REG.cambiarEstadoBtnSalida(false);
    }//GEN-LAST:event_btnExitMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnExit;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblInicioSes;
    private javax.swing.JLabel lbl_registro_email;
    private javax.swing.JLabel lbl_registro_password;
    private javax.swing.JLabel lbl_registro_password_r;
    private javax.swing.JLabel lbl_registro_titulo;
    private javax.swing.JLabel lbl_registro_usuario;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelDesplazamiento;
    private javax.swing.JTextField tFEmail;
    private javax.swing.JPasswordField tFPassword;
    private javax.swing.JPasswordField tFPasswordValidacion;
    private javax.swing.JTextField tFUser;
    // End of variables declaration//GEN-END:variables

    public int getXMouse() {
        return xMouse;
    }

    public int getYyMouse() {
        return yMouse;
    }

    public void setXMouse(int x) {
        xMouse = x;
    }

    public void setYMouse(int y) {
        yMouse = y;
    }
    
    public String getEmail(){
        return tFEmail.getText();
    }
    public String getUser(){
        return tFUser.getText();
    }
    public String getPasswordValidation(){
        return String.valueOf(tFPasswordValidacion.getPassword());
    }
    public String getPassword(){
        return String.valueOf(tFPassword.getPassword());
    }

    public JButton getBtnExit() {
        return btnExit;
    }

    public void setBtnExit(JButton btnExit) {
        this.btnExit = btnExit;
    }

    public JButton getBtnRegistro() {
        return btnRegistro;
    }

    public void setBtnRegistro(JButton btnRegistro) {
        this.btnRegistro = btnRegistro;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JLabel getLblInicioSes() {
        return lblInicioSes;
    }

    public void setLblInicioSes(JLabel lblInicioSes) {
        this.lblInicioSes = lblInicioSes;
    }

    public JLabel getLbl_registro_email() {
        return lbl_registro_email;
    }

    public void setLbl_registro_email(JLabel lbl_registro_email) {
        this.lbl_registro_email = lbl_registro_email;
    }

    public JLabel getLbl_registro_password() {
        return lbl_registro_password;
    }

    public void setLbl_registro_password(JLabel lbl_registro_password) {
        this.lbl_registro_password = lbl_registro_password;
    }

    public JLabel getLbl_registro_password_r() {
        return lbl_registro_password_r;
    }

    public void setLbl_registro_password_r(JLabel lbl_registro_password_r) {
        this.lbl_registro_password_r = lbl_registro_password_r;
    }

    public JLabel getLbl_registro_titulo() {
        return lbl_registro_titulo;
    }

    public void setLbl_registro_titulo(JLabel lbl_registro_titulo) {
        this.lbl_registro_titulo = lbl_registro_titulo;
    }

    public JLabel getLbl_registro_usuario() {
        return lbl_registro_usuario;
    }

    public void setLbl_registro_usuario(JLabel lbl_registro_usuario) {
        this.lbl_registro_usuario = lbl_registro_usuario;
    }

    public JPanel getPanelCentral() {
        return panelCentral;
    }

    public void setPanelCentral(JPanel panelCentral) {
        this.panelCentral = panelCentral;
    }

    public JPanel getPanelDesplazamiento() {
        return panelDesplazamiento;
    }

    public void setPanelDesplazamiento(JPanel panelDesplazamiento) {
        this.panelDesplazamiento = panelDesplazamiento;
    }

    public JTextField gettFEmail() {
        return tFEmail;
    }

    public void settFEmail(JTextField tFEmail) {
        this.tFEmail = tFEmail;
    }

    public JPasswordField gettFPassword() {
        return tFPassword;
    }

    public void settFPassword(JPasswordField tFPassword) {
        this.tFPassword = tFPassword;
    }

    public JPasswordField gettFPasswordValidacion() {
        return tFPasswordValidacion;
    }

    public void settFPasswordValidacion(JPasswordField tFPasswordValidacion) {
        this.tFPasswordValidacion = tFPasswordValidacion;
    }

    public JTextField gettFUser() {
        return tFUser;
    }

    public void settFUser(JTextField tFUser) {
        this.tFUser = tFUser;
    }

    public void limpiarCampos() {
        tFEmail.setText("");
        tFUser.setText("");
        tFPassword.setText("");
        tFPasswordValidacion.setText("");
    }

    public ConexionBDD getConexion() {
        return CON;
    }
    
}
