package vista.frames;

import controlador.ConexionBDD;
import controlador.ControladorLoadingScreen;
import controlador.UtilDiseño;
import javax.swing.JProgressBar;

/**
 * Frame de carga para la aplicacion
 * @author Tomas Gonzalez Martin
 */
public class FrameLoadingScreen extends javax.swing.JFrame {
    /**
     * 
     */
    private FrameLogin ventanaLogin;
    private ConexionBDD con;
    private static ControladorLoadingScreen CLOG;
    /**
     * Creates new form LoadingScreen
     */
    public FrameLoadingScreen() {
        initComponents();
        CLOG = new ControladorLoadingScreen(this);
        /**
         * Llama a la funcion para redondear la ventana
         */
        UtilDiseño.redondearVentana(this);
    }
    /**
     * Inicia la aplicacion y realiza la conexion a la base de datos
     */
    public void inicioAplicacion(){
        /**
         * Contador del porcentaje de la barra de carga
         */
        CLOG.iniciarAplicacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(26, 26, 26));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 40)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mi Aplicacion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 101, 350, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo_LoadingScreen.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 31, 200, 200));

        jProgressBar1.setBackground(new java.awt.Color(217, 217, 217));
        jProgressBar1.setForeground(new java.awt.Color(85, 85, 85));
        jProgressBar1.setValue(50);
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 256, 673, 6));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

    public JProgressBar getProgresBar() {
        return jProgressBar1;
    }

    public void setConexion(ConexionBDD con) {
        this.con = con;
    }

    public ConexionBDD getConexion() {
        return this.con;
    }

    public void setVentanaLogin(FrameLogin frameLogin) {
        this.ventanaLogin = frameLogin;
    }

    public FrameLogin getVentanaLogin() {
        return this.ventanaLogin;
    }
}
