package vista;

import controlador.ControladorLogin;
import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Insets;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

import controlador.ControladorLogin;
/**
 *
 * @author Tomas Gonzalez Martin
 */
public class VentanaLogin extends javax.swing.JFrame {
    
    private int xMouse;
    private int yMouse;
    private ControladorLogin cLog;
    /**
     * Creates new form VentanaLogin
     */
    public VentanaLogin() {
        initComponents();
        
        cLog = new ControladorLogin(this);
        
        Shape s = new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 20, 20);
        setShape(s);
        
        tFUser.putClientProperty( "FlatLaf.style", "arc:30" );
        tFPassword.putClientProperty( "FlatLaf.style", "arc:30" );
        btnIniciar.putClientProperty( "FlatLaf.style", "arc:30" );
        
        tFUser.putClientProperty( FlatClientProperties.PLACEHOLDER_TEXT, "Usuario" );
        tFPassword.putClientProperty( FlatClientProperties.PLACEHOLDER_TEXT, "******************" );
        
        tFUser.putClientProperty("JTextField.padding", new Insets(0,40,0,0));
        tFPassword.putClientProperty("JTextField.padding", new Insets(0,40,0,0));
        
        ImageIcon icon = createImageIcon("src/main/resources/img/IconoUsuario.png", "Icono");
        tFUser.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, icon);
        
        icon = createImageIcon("src/main/resources/img/IconoContraseña.png", "Icono");
        tFPassword.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, icon);
            
    }
    private static ImageIcon createImageIcon(String path, String description) {
        try {
            BufferedImage image = ImageIO.read(new File(path));
            return new ImageIcon(image, description);
        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCentral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblRecuperacion = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        tFPassword = new javax.swing.JPasswordField();
        tFUser = new javax.swing.JTextField();
        lblRegistro = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        panelDesplazamiento = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelCentral.setBackground(new java.awt.Color(26, 26, 26));
        panelCentral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html>\n<div style='text-align: center;'>¡Bienvenido de nuevo!</div>\n</html>");
        panelCentral.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 35, 350, 120));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(164, 164, 164));
        jLabel4.setText("Usuario");
        panelCentral.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 177, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(164, 164, 164));
        jLabel3.setText("Contraseña");
        panelCentral.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 277, -1, -1));

        lblRecuperacion.setForeground(new java.awt.Color(164, 164, 164));
        lblRecuperacion.setText("Recuperar contraseña");
        lblRecuperacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRecuperacionMouseClicked(evt);
            }
        });
        panelCentral.add(lblRecuperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 371, -1, -1));

        btnIniciar.setBackground(new java.awt.Color(158, 255, 0));
        btnIniciar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(0, 0, 0));
        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        panelCentral.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 410, 314, 50));
        panelCentral.add(tFPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 306, 314, 55));
        panelCentral.add(tFUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 210, 314, 55));

        lblRegistro.setForeground(new java.awt.Color(164, 164, 164));
        lblRegistro.setText("Registrate");
        lblRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistroMouseClicked(evt);
            }
        });
        panelCentral.add(lblRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 475, -1, -1));

        btnExit.setBackground(new java.awt.Color(26, 26, 26));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnExit.setText("X");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        panelCentral.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 40, 40));

        panelDesplazamiento.setBackground(new java.awt.Color(26, 26, 26));
        panelDesplazamiento.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelDesplazamientoMouseDragged(evt);
            }
        });
        panelDesplazamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelDesplazamientoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelDesplazamientoLayout = new javax.swing.GroupLayout(panelDesplazamiento);
        panelDesplazamiento.setLayout(panelDesplazamientoLayout);
        panelDesplazamientoLayout.setHorizontalGroup(
            panelDesplazamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        panelDesplazamientoLayout.setVerticalGroup(
            panelDesplazamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        panelCentral.add(panelDesplazamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        cLog.salir();
    }//GEN-LAST:event_btnExitActionPerformed

    private void panelDesplazamientoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDesplazamientoMousePressed
        cLog.desplazamientoPressed(evt);
    }//GEN-LAST:event_panelDesplazamientoMousePressed

    private void panelDesplazamientoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDesplazamientoMouseDragged
        cLog.movimientoPorPantalla(evt);
    }//GEN-LAST:event_panelDesplazamientoMouseDragged

    private void lblRecuperacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRecuperacionMouseClicked
        cLog.abrirVentanaRecuperacion();
        
    }//GEN-LAST:event_lblRecuperacionMouseClicked

    private void lblRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistroMouseClicked
        cLog.abrirVentanaRegistro();
    }//GEN-LAST:event_lblRegistroMouseClicked

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        cLog.iniciarSesion();
    }//GEN-LAST:event_btnIniciarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblRecuperacion;
    private javax.swing.JLabel lblRegistro;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelDesplazamiento;
    private javax.swing.JPasswordField tFPassword;
    private javax.swing.JTextField tFUser;
    // End of variables declaration//GEN-END:variables

    public void setXMouse(int x) {
        xMouse = x;
    }

    public void setYMouse(int y) {
        yMouse = y;
    }

    public int getXMouse() {
       return xMouse;
    }

    public int getYMouse() {
       return yMouse;
    }
    
    public String getUsuario(){
        return tFUser.getText();
    }
    public String getContraseña(){
        return String.valueOf(tFPassword.getPassword());
    }
}
