package vista;

import controlador.UtilDiseño;
import java.awt.CardLayout;
import javax.swing.JButton;
import modelo.Usuario;

/**
 *
 * @author Tomás González Martín
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private int xMouse;
    private int yMouse;
    private final PanelInicio P_INICIO;
    private final PanelServicios P_SERVICIOS;
    private final PanelPeliculas P_PELICULAS;
    private final PanelLibros P_LIBROS;
    private final PanelMusica P_MUSICA;
    private final PanelPerfil P_PERFIL;
    private final CardLayout CARD_LAYOUT;
    private String panelActual;
    /**
     * Creates new form VentanaPrincipal
     * @param user
     */
    public VentanaPrincipal(Usuario user) {
        initComponents();
        CARD_LAYOUT = new CardLayout();
        panelCentral.setLayout(CARD_LAYOUT);
        
        P_INICIO = new PanelInicio();
        P_SERVICIOS = new PanelServicios();
        P_PELICULAS = new PanelPeliculas();
        P_LIBROS = new PanelLibros();
        P_MUSICA = new PanelMusica();
        P_PERFIL = new PanelPerfil();
        
        panelCentral.add(P_INICIO,"pInicio");
        panelCentral.add(P_SERVICIOS,"pServicios");
        
        panelCentral.add(P_PELICULAS,"pPeliculas");
        panelCentral.add(P_LIBROS,"pLibros");
        panelCentral.add(P_MUSICA,"pMusica");
        panelCentral.add(P_PERFIL,"pPerfil");
        
        CARD_LAYOUT.show(panelCentral, "pInicio");
        panelActual = "pInicio";
        
        UtilDiseño.estilizarBotonPanelInicio(btnInicio);
        UtilDiseño.estilizarBotonPanelInicio(btnServicios);
        UtilDiseño.estilizarBotonPanelInicio(btnPeliculas);
        UtilDiseño.estilizarBotonPanelInicio(btnLibros);
        UtilDiseño.estilizarBotonPanelInicio(btnMusica);
        UtilDiseño.estilizarBotonPerfil(btnPerfil);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNavegador = new javax.swing.JPanel();
        btnPerfil = new javax.swing.JButton();
        panelBotonesNav = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnServicios = new javax.swing.JButton();
        btnPeliculas = new javax.swing.JButton();
        btnLibros = new javax.swing.JButton();
        btnMusica = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        panelDesplazamiento = new javax.swing.JPanel();
        panelCentral = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(38, 38, 38));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelNavegador.setBackground(new java.awt.Color(26, 26, 26));
        panelNavegador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPerfil.setBackground(new java.awt.Color(158, 255, 0));
        btnPerfil.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPerfil.setText("Perfil");
        btnPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPerfil.setFocusPainted(false);
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });
        panelNavegador.add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(1348, 20, 102, 59));

        panelBotonesNav.setBackground(new java.awt.Color(26, 26, 26));

        btnInicio.setBackground(new java.awt.Color(38, 38, 38));
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("Inicio");
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.setFocusPainted(false);
        btnInicio.setMargin(new java.awt.Insets(11, 20, 12, 20));
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInicioMouseExited(evt);
            }
        });
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        panelBotonesNav.add(btnInicio);

        btnServicios.setBackground(new java.awt.Color(38, 38, 38));
        btnServicios.setForeground(new java.awt.Color(255, 255, 255));
        btnServicios.setText("Servicios");
        btnServicios.setContentAreaFilled(false);
        btnServicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnServicios.setFocusPainted(false);
        btnServicios.setMargin(new java.awt.Insets(11, 20, 12, 20));
        btnServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnServiciosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnServiciosMouseExited(evt);
            }
        });
        btnServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiciosActionPerformed(evt);
            }
        });
        panelBotonesNav.add(btnServicios);

        btnPeliculas.setBackground(new java.awt.Color(38, 38, 38));
        btnPeliculas.setForeground(new java.awt.Color(255, 255, 255));
        btnPeliculas.setText("Peliculas");
        btnPeliculas.setContentAreaFilled(false);
        btnPeliculas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPeliculas.setFocusPainted(false);
        btnPeliculas.setMargin(new java.awt.Insets(11, 20, 12, 20));
        btnPeliculas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPeliculasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPeliculasMouseExited(evt);
            }
        });
        btnPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeliculasActionPerformed(evt);
            }
        });
        panelBotonesNav.add(btnPeliculas);

        btnLibros.setBackground(new java.awt.Color(38, 38, 38));
        btnLibros.setForeground(new java.awt.Color(255, 255, 255));
        btnLibros.setText("Libros");
        btnLibros.setContentAreaFilled(false);
        btnLibros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLibros.setFocusPainted(false);
        btnLibros.setMargin(new java.awt.Insets(11, 20, 12, 20));
        btnLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLibrosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLibrosMouseExited(evt);
            }
        });
        btnLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibrosActionPerformed(evt);
            }
        });
        panelBotonesNav.add(btnLibros);

        btnMusica.setBackground(new java.awt.Color(38, 38, 38));
        btnMusica.setForeground(new java.awt.Color(255, 255, 255));
        btnMusica.setText("Musica");
        btnMusica.setContentAreaFilled(false);
        btnMusica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMusica.setFocusPainted(false);
        btnMusica.setMargin(new java.awt.Insets(11, 20, 12, 20));
        btnMusica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMusicaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMusicaMouseExited(evt);
            }
        });
        btnMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMusicaActionPerformed(evt);
            }
        });
        panelBotonesNav.add(btnMusica);

        panelNavegador.add(panelBotonesNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 21, 468, 53));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo_Nav.png"))); // NOI18N
        panelNavegador.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 20, 60, 60));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mi Aplicacion");
        panelNavegador.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 37, -1, -1));

        btnExit.setBackground(new java.awt.Color(26, 26, 26));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnExit.setForeground(new java.awt.Color(164, 164, 164));
        btnExit.setText("X");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setFocusable(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        panelNavegador.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1495, 0, 40, 40));

        panelDesplazamiento.setBackground(new java.awt.Color(26, 26, 26));
        panelDesplazamiento.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelDesplazamientoMouseDragged(evt);
            }
        });
        panelDesplazamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelDesplazamientoMousePressed(evt);
            }
        });
        panelNavegador.add(panelDesplazamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 20));

        getContentPane().add(panelNavegador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1536, 100));

        panelCentral.setBackground(new java.awt.Color(38, 38, 38));
        panelCentral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panelCentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1536, 730));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panelDesplazamientoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDesplazamientoMouseDragged
        int x =  evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_panelDesplazamientoMouseDragged

    private void panelDesplazamientoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDesplazamientoMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panelDesplazamientoMousePressed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiciosActionPerformed
        CARD_LAYOUT.show(panelCentral, "pServicios");
        panelActual = "pServicios";
        UtilDiseño.eliminarFondoBtnsPaneInicio(this);
        UtilDiseño.btnPaneInicioActivo(btnServicios);
    }//GEN-LAST:event_btnServiciosActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        CARD_LAYOUT.show(panelCentral, "pInicio");
        panelActual = "pInicio";
        UtilDiseño.eliminarFondoBtnsPaneInicio(this);
        UtilDiseño.btnPaneInicioActivo(btnInicio);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeliculasActionPerformed
        CARD_LAYOUT.show(panelCentral, "pPeliculas");
        panelActual = "pPeliculas";
        UtilDiseño.eliminarFondoBtnsPaneInicio(this);
        UtilDiseño.btnPaneInicioActivo(btnPeliculas);
    }//GEN-LAST:event_btnPeliculasActionPerformed

    private void btnLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibrosActionPerformed
        CARD_LAYOUT.show(panelCentral, "pLibros");
        panelActual = "pLibros";
        UtilDiseño.eliminarFondoBtnsPaneInicio(this);
        UtilDiseño.btnPaneInicioActivo(btnLibros);
    }//GEN-LAST:event_btnLibrosActionPerformed

    private void btnMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMusicaActionPerformed
        CARD_LAYOUT.show(panelCentral, "pMusica");
        panelActual = "pMusica";
        UtilDiseño.eliminarFondoBtnsPaneInicio(this);
        UtilDiseño.btnPaneInicioActivo(btnMusica);
    }//GEN-LAST:event_btnMusicaActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        CARD_LAYOUT.show(panelCentral, "pPerfil");
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnServiciosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServiciosMouseEntered
        UtilDiseño.btnPaneInicioActivo(btnServicios);
    }//GEN-LAST:event_btnServiciosMouseEntered

    private void btnServiciosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServiciosMouseExited
        if(!panelActual.equals("pServicios"))
            UtilDiseño.eliminarFondoBtnPaneInicio(btnServicios);
    }//GEN-LAST:event_btnServiciosMouseExited

    private void btnPeliculasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPeliculasMouseEntered
        UtilDiseño.btnPaneInicioActivo(btnPeliculas);
    }//GEN-LAST:event_btnPeliculasMouseEntered

    private void btnPeliculasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPeliculasMouseExited
       if(!panelActual.equals("pPeliculas"))
            UtilDiseño.eliminarFondoBtnPaneInicio(btnPeliculas);
    }//GEN-LAST:event_btnPeliculasMouseExited

    private void btnMusicaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMusicaMouseEntered
        UtilDiseño.btnPaneInicioActivo(btnMusica);
    }//GEN-LAST:event_btnMusicaMouseEntered

    private void btnMusicaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMusicaMouseExited
        if(!panelActual.equals("pMusica"))
            UtilDiseño.eliminarFondoBtnPaneInicio(btnMusica);        
    }//GEN-LAST:event_btnMusicaMouseExited

    private void btnLibrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibrosMouseEntered
        UtilDiseño.btnPaneInicioActivo(btnLibros);
    }//GEN-LAST:event_btnLibrosMouseEntered

    private void btnLibrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibrosMouseExited
        if(!panelActual.equals("pLibros"))
            UtilDiseño.eliminarFondoBtnPaneInicio(btnLibros);   
    }//GEN-LAST:event_btnLibrosMouseExited

    private void btnInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseEntered
        UtilDiseño.btnPaneInicioActivo(btnInicio);
    }//GEN-LAST:event_btnInicioMouseEntered

    private void btnInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseExited
        if(!panelActual.equals("pInicio"))
            UtilDiseño.eliminarFondoBtnPaneInicio(btnInicio);
    }//GEN-LAST:event_btnInicioMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnLibros;
    private javax.swing.JButton btnMusica;
    private javax.swing.JButton btnPeliculas;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnServicios;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panelBotonesNav;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelDesplazamiento;
    private javax.swing.JPanel panelNavegador;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnInicio() {
        return btnInicio;
    }

    public JButton getBtnServicios() {
        return btnServicios;
    }

    public JButton getBtnPeliculas() {
        return btnPeliculas;
    }

    public JButton getBtnLibros() {
        return btnLibros;
    }

    public JButton getBtnMusica() {
        return btnMusica;
    }
}
