package vista.modulos;

import modelo.Cancion;

/**
 * Este módulo representa una canción en la interfaz de usuario.
 * Proporciona información sobre la canción, como su título, autor, puntuación y duración.
 * Este módulo se puede utilizar para mostrar información detallada sobre una canción en la interfaz de usuario.
 * @author Tomás González Martín
 */
public class ModuloCancion extends javax.swing.JPanel {

    /**
     * Crea un nuevo módulo de canción con la información proporcionada por el objeto Cancion.
     * @param cancion El objeto Cancion que contiene la información de la canción.
     */
    public ModuloCancion(Cancion cancion) {
        initComponents();
        //lblImagen.setIcon(cancion.getImagen());
        lblTitulo.setText(cancion.getTitulo()+","+cancion.getAutor());
        lblPuntacion.setText(String.valueOf(cancion.getPuntuacion())+"/5");
        lblDuracion.setText(String.valueOf(cancion.getDuracion()+"'"));
    }
     /**
     * Crea un nuevo módulo de canción sin información inicial.
     */   
    public ModuloCancion(){
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagen = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblDuracion = new javax.swing.JLabel();
        lblPuntacion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(38, 38, 38));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/canciones/logo_cancion_default.png"))); // NOI18N
        add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 132, 180));

        lblTitulo.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitulo.setText("Titulo,autor");
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 118, 620, -1));

        lblDuracion.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblDuracion.setForeground(new java.awt.Color(255, 255, 255));
        lblDuracion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDuracion.setText("Duracion");
        add(lblDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(914, 118, 110, 41));

        lblPuntacion.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblPuntacion.setForeground(new java.awt.Color(255, 255, 255));
        lblPuntacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPuntacion.setText("Score");
        add(lblPuntacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1021, 118, 70, 41));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Star.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 118, 41, 41));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblPuntacion;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
