package vista.modulos;

import modelo.Servicio;

/**
 *
 * @author Tomás González Martín
 */
public class ModuloServicio extends javax.swing.JPanel {

    /**
     * Creates new form Servicio
     * @param servicio
     */
    public ModuloServicio(Servicio servicio) {
        initComponents();
        lblImagen.setIcon(servicio.getImagen());
        lblTitulo.setText(servicio.getNombre());
        lblDescripcion.setText("<html><div style='text-align: justify;'>"+servicio.getDescripcion()+"</div></html>");
    }
    public ModuloServicio(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagen = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();

        setBackground(new java.awt.Color(38, 38, 38));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logos_servicios/LogoServiciosAmazon.png"))); // NOI18N
        add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 62, 290, 88));

        lblTitulo.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Titulo");
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 300, -1));

        lblDescripcion.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(230, 230, 230));
        lblDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDescripcion.setText("<html>\n<div style=\"text-align: justify;\">\nAt Squareup, our design team is passionate about creating stunning, user-centric designs that captivate your audience and elevate your brand. We believe that great design is not just about aesthetics; it's about creating seamless and intuitive user experiences.\n</div>\n</html>");
        lblDescripcion.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(lblDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 255, 303, 230));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
